/*
 * VTB Group. Do not reproduce without permission in writing.
 * Copyright (c) 2019 VTB Group. All rights reserved.
 */
export const STATUSES = {
    ALL: 'ALL',
    FAVORITE: 'FAVORITE',
    DETAILS_ERROR: 'DETAILS_ERROR',
    DRAFT: 'DRAFT',
    EXECUTED_BY_CLIENT: 'EXECUTED_BY_CLIENT',
    EXECUTED: 'EXECUTED',
    NEW: 'NEW',
    OBTAINED_BY_BANK: 'OBTAINED_BY_BANK',
    OBTAINED_BY_CLIENT: 'OBTAINED_BY_CLIENT',
    PARTLY_SIGNED_BY_BANK: 'PARTLY_SIGNED_BY_BANK',
    PARTLY_SIGNED: 'PARTLY_SIGNED',
    RECALLED_BY_BANK: 'RECALLED_BY_BANK',
    RECALLED: 'RECALLED',
    REJECTED: 'REJECTED',
    SENDING: 'SENDING',
    SIGNED_BY_BANK: 'SIGNED_BY_BANK',
    SIGNED: 'SIGNED',
    WRONG_E_SIGNATURE: 'WRONG_E_SIGNATURE',
    IN_PROCESS: 'IN_PROCESS',
    DELIVERED: 'DELIVERED',
    CHECKED_DETAILES_RECEIVING: 'CHECKED_DETAILES_RECEIVING',
    CORRECT_REQUISITES: 'CORRECT_REQUISITES', // TODO [sf] 03-Oct-18 specify at analytics, for v1.1?
    IN_WORKING: 'IN_WORKING',
    TO_SIGN: 'TO_SIGN',
    COMPLETED: 'COMPLETED',
    UNASSIGNED: 'UNASSIGNED',
    TROUBLED: 'TROUBLED',
    INCOMING: 'INCOMING',
    TO_SEND: 'TO_SEND',
    DELETED: 'DELETED',
    NOT_RECEIVED_BY_ABS: 'NOT_RECEIVED_BY_ABS'
};
export const FILTERS_CATEGORY_ALL = 'filters.all';
