/*
 * VTB Group. Do not reproduce without permission in writing.
 * Copyright (c) 2019 VTB Group. All rights reserved.
 */
export const STATUSES_PARTIAL = {
    ALL: 'ALL',
    FAVORITE: 'FAVORITE',
    EMPLOYEE_NOT_ASSIGNED: 'EMPLOYEE_NOT_ASSIGNED',
    EMPLOYEE_TO_BANK_IN_PROCESS: 'EMPLOYEE_TO_BANK_IN_PROCESS',
    EMPLOYEE_TO_BANK_EXECUTED: 'EMPLOYEE_TO_BANK_EXECUTED',
    EMPLOYEE_PROBLEMS: 'EMPLOYEE_PROBLEMS',
    EMPLOYEE_IN_PROCESS: 'EMPLOYEE_IN_PROCESS',
    EMPLOYEE_TO_SIGN: 'EMPLOYEE_TO_SIGN',
    EMPLOYEE_TO_SEND: 'EMPLOYEE_TO_SEND',
    EMPLOYEE_PROCESSING: 'EMPLOYEE_PROCESSING',
    EMPLOYEE_EXECUTED: 'EMPLOYEE_EXECUTED',
    CLIENT_PROCESSING: 'CLIENT_PROCESSING',
    TO_SIGN: 'TO_SIGN',
    TO_BE_SENT: 'TO_BE_SENT',
    CLIENT_IN_PROCESS: 'CLIENT_IN_PROCESS',
    EXECUTED: 'EXECUTED',
    INCOMING: 'INCOMING',
    WERE_READ: 'WERE_READ',
    RECALLED_BY_BANK: 'RECALLED_BY_BANK'
};
