/*
 * VTB Group. Do not reproduce without permission in writing.
 * Copyright (c) 2019 VTB Group. All rights reserved.
 */
import {DOCUMENT_STATUS_FILTERS} from './../../../../../modules/filters';

export const employeeStatusFilters = [
    DOCUMENT_STATUS_FILTERS.CLIENT_PROCESSING,
    DOCUMENT_STATUS_FILTERS.TO_SIGN,
    DOCUMENT_STATUS_FILTERS.TO_BE_SENT,
    DOCUMENT_STATUS_FILTERS.CLIENT_IN_PROCESS,
    DOCUMENT_STATUS_FILTERS.EXECUTED,
    DOCUMENT_STATUS_FILTERS.INCOMING,
    DOCUMENT_STATUS_FILTERS.WERE_READ,
    DOCUMENT_STATUS_FILTERS.RECALLED_BY_BANK,
    DOCUMENT_STATUS_FILTERS.FAVORITE,
    DOCUMENT_STATUS_FILTERS.ALL
];
